name: repository_size
on: [push]
jobs:
  repository_size:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get repository size
        run: |
          echo ${GITHUB_REF##"/}
          du -skh --exclude=".git"
