name: what_time_is_it
on: [push]
jobs:
  what_time_is_it:
    runs-on: ubuntu-latest
    steps:
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}